### ISSUE TITLE
Incorrect Permissions for Fingerbank Conf

### ISSUE THREAD

**Issue by mcaulifn** [inverse-inc/ansible-packetfence#44]
Packetfence services require `read` access to `fingerbank.conf`.  The current task sets permissions to `0660` which does not give the `pf` user access to this file.

```
/usr/local/pf/bin/pfcmd configreload hard
Failed to open /usr/local/fingerbank/conf/fingerbank.conf: Permission denied at /usr/local/pf/lib/pfconfig/namespaces/config.pm line 60.
cannot create a tied pf::IniFiles at /usr/local/pf/lib/pf/IniFiles.pm line 414.
```

https://github.com/inverse-inc/ansible-packetfence/blob/9a3ba59feb3ca6a37918437b683ddaf0cc2d9666/packetfence/roles/packetfence_install/tasks/config.yml#L29

@nqb Can you take a look at this one?

**Comment by nqb** [comment]
Hello @mcaulifn,

I will provide an answer on this.

**Comment by nqb** [comment]
I will remove mode `0660` for following reasons:
- `pfcmd fixpermissions` modify mode to `0664`
- for an unknown reason having a mode of `0660` on that file cause issue you reported. I don't see why because `pf` is member of `fingerbank` group and have access to that file.
- we will rework permissions in future releases.
